### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by hubdotcom** [gingeleski/jawfish#1]
``` python
python /jawfish/run.py 
Traceback (most recent call last):
  File "/jawfish/run.py", line 2, in <module>
    from jawfish import app
  File "/jawfish/jawfish/__init__.py", line 1, in <module>
    from flask import Flask
ImportError: No module named flask
```

**Comment by gingeleski** [comment]
[Clarified.](https://github.com/gingeleski/jawfish/blob/master/README.md#trying-to-run-jawfish-locally)
